# Generated by Django 3.2.4 on 2023-03-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YandexSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('token', models.CharField(max_length=200, verbose_name='OAuth-токен')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
            ],
        ),
    ]
