# Generated by Django 3.2.4 on 2023-04-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20230403_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryhistory',
            name='six_numbers',
            field=models.CharField(default='936397', max_length=200, verbose_name='код для курьера'),
        ),
        migrations.AlterField(
            model_name='deliveryhistory',
            name='uuid',
            field=models.CharField(default='964feadf-4678-446e-a0d7-3b4c1713ae34', max_length=200),
        ),
        migrations.AlterField(
            model_name='yandexsettings',
            name='emergency_contact_phone',
            field=models.CharField(default='', help_text='Телефон контактного лица', max_length=200),
        ),
        migrations.AlterField(
            model_name='yandexsettings',
            name='referral_source',
            field=models.CharField(default='', help_text='Источник заявки (можно передать наименование CMS, из которой создается запрос)', max_length=200),
        ),
    ]
