# Generated by Django 3.2.4 on 2023-04-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_auto_20230405_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryhistory',
            name='six_numbers',
            field=models.CharField(default='459864', max_length=200, verbose_name='код для курьера'),
        ),
        migrations.AlterField(
            model_name='deliveryhistory',
            name='uuid',
            field=models.CharField(default='6538e79f-e0b6-4e5f-8f07-8a23a2426cff', max_length=200),
        ),
    ]
