# Generated by Django 3.2.4 on 2023-04-07 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_auto_20230405_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='yandexsettings',
            name='email',
            field=models.CharField(default='₽', help_text='Email', max_length=200),
        ),
        migrations.AlterField(
            model_name='deliveryhistory',
            name='six_numbers',
            field=models.CharField(default='387106', max_length=200, verbose_name='код для курьера'),
        ),
        migrations.AlterField(
            model_name='deliveryhistory',
            name='uuid',
            field=models.CharField(default='82a6a7c0-8b17-40d0-af57-07111bef610b', max_length=200),
        ),
    ]
