# Generated by Django 3.2.4 on 2023-04-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_auto_20230407_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryhistory',
            name='six_numbers',
            field=models.CharField(default='471582', max_length=200, verbose_name='код для курьера'),
        ),
        migrations.AlterField(
            model_name='deliveryhistory',
            name='uuid',
            field=models.CharField(default='74789f8b-72a2-48d0-b285-008af6d24480', max_length=200),
        ),
        migrations.AlterField(
            model_name='yandexsettings',
            name='email',
            field=models.CharField(default='', help_text='Email', max_length=200),
        ),
    ]
