# Generated by Django 3.2.4 on 2023-04-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_auto_20230407_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryhistory',
            name='six_numbers',
            field=models.CharField(default='', max_length=200, verbose_name='код для курьера'),
        ),
        migrations.AlterField(
            model_name='deliveryhistory',
            name='uuid',
            field=models.CharField(default='', max_length=200),
        ),
    ]
