# Generated by Django 3.2.4 on 2023-04-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_auto_20230407_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='yandexsettings',
            name='test_phone',
            field=models.CharField(default='', help_text='Телефон для тестового заказа', max_length=200),
        ),
    ]
