# Generated by Django 3.2.4 on 2023-04-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_yandexsettings_test_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='yandexsettings',
            name='latitude',
            field=models.FloatField(default=55.196829, verbose_name='тестовая Широта'),
        ),
        migrations.AddField(
            model_name='yandexsettings',
            name='longitude',
            field=models.FloatField(default=61.395762, verbose_name='тестовая Долгота'),
        ),
    ]
