# Generated by Django 3.2.4 on 2023-04-11 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_auto_20230407_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='yandexsettings',
            name='geocoder_key',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='ключ геокодера'),
        ),
    ]
