# Generated by Django 3.2.4 on 2023-04-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_auto_20230413_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydistance',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
