# Generated by Django 3.2.4 on 2023-04-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0014_deliverydistance_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverydistance',
            name='active',
        ),
        migrations.AddField(
            model_name='deliverysettings',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
