# Generated by Django 3.2.4 on 2023-04-16 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0073_servicepoint_phone'),
        ('delivery', '0015_auto_20230413_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydistance',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shaw_queue.menu', verbose_name='Menu Item'),
        ),
    ]
