# Generated by Django 3.2.4 on 2023-04-16 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0073_servicepoint_phone'),
        ('delivery', '0016_deliverydistance_menu_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryhistory',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryhistory',
            name='coordinates',
            field=models.CharField(default='', max_length=100, verbose_name='coordinates'),
        ),
        migrations.AddField(
            model_name='deliveryhistory',
            name='daily_number',
            field=models.CharField(default='', max_length=50, verbose_name='daily_number'),
        ),
        migrations.AddField(
            model_name='deliveryhistory',
            name='delivery_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shaw_queue.menu', verbose_name='delivery_menu'),
        ),
        migrations.AddField(
            model_name='deliveryhistory',
            name='delivery_price',
            field=models.IntegerField(default=0, verbose_name='delivery_price'),
        ),
        migrations.AddField(
            model_name='deliveryhistory',
            name='description',
            field=models.CharField(default='', max_length=500, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='deliveryhistory',
            name='door_code',
            field=models.CharField(default='', max_length=100, verbose_name='door_code'),
        ),
        migrations.AddField(
            model_name='deliveryhistory',
            name='full_price',
            field=models.IntegerField(default=0, verbose_name='full_price'),
        ),
        migrations.AddField(
            model_name='deliveryhistory',
            name='items',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryhistory',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='deliveryhistory',
            name='phone',
            field=models.CharField(default='', max_length=100, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='deliveryhistory',
            name='porch',
            field=models.CharField(default='', max_length=100, verbose_name='porch'),
        ),
        migrations.AddField(
            model_name='deliveryhistory',
            name='sflat',
            field=models.CharField(default='', max_length=100, verbose_name='sflat'),
        ),
        migrations.AddField(
            model_name='deliveryhistory',
            name='sfloor',
            field=models.CharField(default='', max_length=100, verbose_name='sfloor'),
        ),
    ]
