# Generated by Django 3.2.4 on 2023-04-20 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0074_order_delivery_daily_number'),
        ('delivery', '0018_auto_20230416_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryhistory',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shaw_queue.order'),
        ),
    ]
