# Generated by Django 3.2.4 on 2023-04-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0019_deliveryhistory_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryhistory',
            name='confirm',
            field=models.BooleanField(default=False, help_text='заявка подтверждена'),
        ),
    ]
