# Generated by Django 3.2.4 on 2023-04-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0020_deliveryhistory_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryhistory',
            name='claim_id',
            field=models.CharField(default='', max_length=50, verbose_name='claim_id'),
        ),
    ]
