# Generated by Django 3.2.4 on 2023-05-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0021_deliveryhistory_claim_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryhistory',
            name='description',
            field=models.CharField(default='', max_length=500, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='deliveryhistory',
            name='items',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryhistory',
            name='phone',
            field=models.CharField(default='', max_length=100, verbose_name='phone'),
        ),
    ]
