# Generated by Django 3.2.4 on 2023-05-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0022_auto_20230502_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryhistory',
            name='fullname',
            field=models.CharField(default='', max_length=500, verbose_name='fullname'),
        ),
        migrations.AlterField(
            model_name='deliveryhistory',
            name='description',
            field=models.CharField(blank=True, default='Челябинск, Россия', max_length=500, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='deliveryhistory',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='phone'),
        ),
    ]
