# Generated by Django 3.2.4 on 2023-05-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0023_auto_20230502_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryhistory',
            name='logg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
