# Generated by Django 3.2.4 on 2023-05-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0024_deliveryhistory_logg'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryhistory',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'новый'), ('estimating', 'оценка'), ('estimating_failed', 'Ошибка_оценки'), ('ready_for_approval', 'готов_к_одобрению'), ('accepted', 'принято'), ('performer_lookup', 'исполнитель_поиск'), ('performer_draft', 'исполнитель_проект'), ('performer_found', 'найденный исполнитель'), ('performer_not_found', 'исполнитель не найден'), ('pickup_arrived', 'самовывоз прибыл'), ('ready_for_pickup_confirmation', 'готово к подтверждению получения'), ('pickuped', 'забрано'), ('delivery_arrived', 'доставка прибыла'), ('ready_for_delivery_confirmation', 'готово к подтверждению доставки'), ('pay_waiting', 'ожидание оплаты'), ('delivered', 'доставлено'), ('delivered_finish', 'доставлено (завершено)'), ('returning', 'возвращение'), ('return_arrived', 'возврат прибыл'), ('ready_for_return_confirmation', 'готово к подтверждению возврата'), ('returned', 'возвращено'), ('returned_finish', 'возвращено (завершено)'), ('failed', 'ошибка'), ('cancelled', 'отмена'), ('cancelled_with_payment', 'отменено с оплатой'), ('cancelled_by_taxi', 'отменено на такси'), ('cancelled_with_items_on_hands', 'отменено с продуктами на руках')], default='new', max_length=100, verbose_name='status'),
        ),
    ]
