# Generated by Django 3.2.4 on 2023-05-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0025_deliveryhistory_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverys', models.ManyToManyField(blank=True, to='delivery.DeliveryHistory', verbose_name='доставки')),
            ],
        ),
    ]
