# Generated by Django 3.2.4 on 2023-05-25 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0026_deliverychecklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryActive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.deliveryhistory')),
            ],
        ),
        migrations.DeleteModel(
            name='DeliveryCheckList',
        ),
    ]
