# Generated by Django 3.2.4 on 2023-06-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0027_auto_20230525_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryhistory',
            name='city',
            field=models.CharField(default='', max_length=500, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='deliveryhistory',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryhistory',
            name='country',
            field=models.CharField(default='', max_length=500, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='deliveryhistory',
            name='door_code',
            field=models.CharField(default='', max_length=100, verbose_name='door_code'),
        ),
        migrations.AddField(
            model_name='deliveryhistory',
            name='latitude',
            field=models.CharField(default='', max_length=500, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='deliveryhistory',
            name='longitude',
            field=models.CharField(default='', max_length=500, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='deliveryhistory',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='deliveryhistory',
            name='porch',
            field=models.CharField(default='', max_length=100, verbose_name='porch'),
        ),
        migrations.AddField(
            model_name='deliveryhistory',
            name='sflat',
            field=models.CharField(default='', max_length=100, verbose_name='sflat'),
        ),
        migrations.AddField(
            model_name='deliveryhistory',
            name='sfloor',
            field=models.CharField(default='', max_length=100, verbose_name='sfloor'),
        ),
        migrations.AddField(
            model_name='deliveryhistory',
            name='wait_minutes',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='ожидать минут'),
        ),
    ]
