from django.conf.urls import url
from django.urls import path
from . import views
# test
urlpatterns = [

    path('test/test', views.test, name='test_test'),

    path('buyer_queue/new', views.buyer_queue_new, name='buyer_queue_new'),
    path('ajax/buyer_queue/new', views.buyer_queue_ajax_new, name='buyer_queue_ajax_new'),  # del me after, Im copy

    path('delivery/create/', views.delivery, name='delivery-sms'),
    path('api/delivery/create/', views.api_delivery, name='api-delivery-sms'),

    path('api/sms/pay/', views.api_sms_pay, name='api-sms-pay'),

    url(r'^$', views.welcomer, name='welcomer'),
    url(r'^reload_menu', views.get_1c_menu, name='reload_menu'),
    url(r'^order_status', views.recive_1c_order_status, name='order_status'),
    url(r'^menu/$', views.menu, name='menu'),
    url(r'^order_display', views.order_display, name='order_display'),
    url(r'^new_menu/$', views.new_menu, name='new_menu'),
    url(r'^delivery_interface', views.delivery_interface, name='delivery_interface'),
    url(r'^ats_listner', views.ats_listner, name='ats_listner'),
    url(r'^cook_pause', views.cook_pause, name="cook_pause"),
    url(r'^aux_control_page', views.aux_control_page, name="aux_control_page"),
    url(r'^order/1c_payment_result/$', views.order_1c_payment, name="order_1c_payment"),
    url(r'^order/print/(?P<order_id>[0-9]+)/$', views.print_order, name="order_print"),
    url(r'^order/voice/(?P<order_id>[0-9]+)/$', views.voice_order, name="voice_order"),
    url(r'^order/(?P<order_id>[0-9]+)/$', views.order_content, name="order_content"),
    url(r'^close_all/$', views.close_all, name="close_all"),
    url(r'^voice_all/$', views.voice_all, name="voice_all"),
    url(r'^ajax/delivery_workspace_update', views.delivery_workspace_update, name="delivery-workspace-update"),
    url(r'^ajax/check_calls', views.check_incoming_calls, name="check_calls"),
    url(r'^ajax/delivery_order', views.DeliveryOrderViewAJAX.as_view(), name="delivery-order-ajax"),
    url(r'^ajax/print_delivery_order_id', views.print_delivery_order, name="delivery_order_print"),
    url(r'^ajax/search_comment', views.search_comment, name="search_comment"),
    url(r'^ajax/unvoice', views.unvoice_order, name="unvoice_order"),
    url(r'^ajax/select_order', views.select_order, name="select_order"),
    url(r'^ajax/select_cook', views.select_cook, name="select_cook"),
    url(r'^ajax/change_cook', views.change_cook, name="change_cook"),
    url(r'^ajax/start_shawarma_preparation', views.start_shawarma_preparation, name="start_shawarma_preparation"),
    url(r'^ajax/start_shawarma_cooking', views.start_shawarma_cooking, name="start_shawarma_cooking"),
    url(r'^ajax/start_shashlyk_cooking', views.start_shashlyk_cooking, name="start_shashlyk_cooking"),
    url(r'^ajax/finish_shashlyk_cooking', views.finish_shashlyk_cooking, name="finish_shashlyk_cooking"),
    url(r'^ajax/finish_delivery_order', views.finish_delivery_order, name="finish_delivery_order"),
    url(r'^ajax/deliver_delivery_order', views.deliver_delivery_order, name="deliver_delivery_order"),
    url(r'^ajax/check_delivery_order', views.check_delivery_order, name="check_delivery_order"),
    url(r'^ajax/cancel_delivery_order', views.cancel_delivery_order, name="cancel_delivery_order"),
    url(r'^ajax/start_delivery', views.start_delivery, name="start_delivery"),
    url(r'^ajax/cancel_delivery', views.cancel_delivery, name="cancel_delivery"),
    url(r'^ajax/order_specifics', views.order_specifics, name="order_specifics"),
    url(r'^ajax/start_long_poll', views.long_poll_handler, name="start_long_poll"),
    url(r'^ajax/respond_long_poll', views.flag_changer, name="respond_long_poll"),
    url(r'^ajax/update_commodity', views.update_commodity, name="update_commodity"),
    url(r'^ajax/get_content_page', views.get_content_page, name="get_content_page"),
    url(r'^ajax/status_refresh', views.status_refresher, name="status_refresh"),
    url(r'^ajax/make_order', views.make_order, name="make_order"),
    url(r'^ajax/buyer_queue/vertical', views.buyer_queue_vertical_ajax, name="buyer_queue_vertical_ajax"),
    url(r'^ajax/buyer_queue', views.buyer_queue_ajax, name="buyer_queue_ajax"),
    url(r'^ajax/close_order', views.close_order_view, name="close_order"),
    url(r'^ajax/ready_order', views.ready_order, name="ready_order"),
    url(r'^ajax/pay_order', views.pay_order, name="pay_order"),
    url(r'^ajax/cancel_item', views.cancel_item, name="cancel_item"),
    url(r'^ajax/cancel_order', views.cancel_order_view, name="cancel_order"),
    url(r'^ajax/next_to_prepare', views.next_to_prepare, name="next_to_prepare"),
    url(r'^ajax/take', views.take, name="take"),
    url(r'^ajax/to_grill', views.to_grill, name="to_grill"),
    url(r'^ajax/grill_timer', views.grill_timer, name="grill_timer"),
    url(r'^ajax/finish_cooking', views.finish_cooking, name="finish_cooking"),
    url(r'^ajax/grill_all_content', views.grill_all_content, name="grill_all_content"),
    url(r'^ajax/finish_all_content', views.finish_all_content, name="finish_all_content"),
    url(r'^ajax/finish_supplement', views.finish_supplement, name="finish_supplement"),
    url(r'^ajax/update_item_quantity', views.update_item_quantity, name="update_item_quantity"),
    url(r'^ajax/current_queue', views.current_queue_ajax, name="current_queue_ajax"),
    url(r'^ajax/statistics', views.statistic_page_ajax, name="update_statistics"),
    url(r'^ajax/not_paid_statistics', views.not_paid_statistics_ajax, name="update_not_paid_statistics"),
    url(r'^ajax/opinion_statistics', views.opinion_statistics_ajax, name="update_opinion_statistics"),
    url(r'^ajax/pause_statistics', views.pause_statistic_page_ajax, name="update_pause_statistics"),
    url(r'^ajax/records_statistics', views.call_record_page_ajax, name="update_records_statistics"),
    url(r'^ajax/s_order_shashlychnik', views.shashlychnik_select_order, name="select_order_shashlychnik"),
    url(r'^ajax/s_order_burgerman', views.burgerman_select_order, name="select_order_burgerman"),
    url(r'^ajax/s_order_barista', views.barista_select_order, name="select_order_barista"),
    url(r'^ajax/cooks_content_info', views.cooks_content_info_ajax, name="cooks_content_info_ajax"),
    url(r'^current_queue', views.current_queue, name="current_queue"),
    url(r'^production_queue', views.production_queue, name="production_queue"),
    url(r'^order_history', views.order_history, name="order_history"),
    url(r'^cook_interface', views.cook_interface, name="cook_interface"),
    url(r'^c_i_a', views.c_i_a, name="cook_interface_ajax"),
    url(r'^shashlychnik_interface', views.shashlychnik_interface, name="shashlychnik_interface"),

    url(r'^burgerman_interface', views.burgerman_interface, name="burgerman_interface"),
    url(r'^barista_interface', views.barista_interface, name="barista_interface"),

    url(r'^s_i_ajax', views.s_i_a, name="shashlychnik_interface_ajax"),
    url(r'^burger_i_ajax', views.burger_i_ajax, name="burgerman_interface_ajax"),
    url(r'^coffee_i_ajax', views.coffee_i_ajax, name="barista_interface_ajax"),
    url(r'^redirection', views.redirection, name="redirection"),

    path('new_order_history/', views.order_history_new, name='order_history_new'),

    path('buyer_queue/black/vertical/', views.buyer_queue_black_vertical, name='buyer_queue_black_vertical'),
    path('buyer_queue/black/', views.buyer_queue_black, name='buyer_queue_black'),
    path('buyer_queue/vertical/', views.buyer_queue_vertical, name='buyer_queue_vertical'),
    path('buyer_queue/', views.buyer_queue, name='buyer_queue'),

    path('buyer_queue/<str:px>/black/vertical/', views.buyer_queue_black_vertical_px, name='buyer_queue_black_vertical_px'),
    path('buyer_queue/<str:px>/black/', views.buyer_queue_black_px, name='buyer_queue_black_px'),
    path('buyer_queue/<str:px>/vertical/', views.buyer_queue_vertical_px, name='buyer_queue_vertical_px'),
    path('buyer_queue/<str:px>/', views.buyer_queue_px, name='buyer_queue_px'),


    url(r'^statistics', views.statistic_page, name="statistics"),
    url(r'^not_paid_statistics', views.not_paid_statistics, name="not_paid_statistics"),
    url(r'^opinion_statistics', views.opinion_statistics, name="opinion_statistics"),
    url(r'^pause_statistics', views.pause_statistic_page, name="pause_statistics"),
    url(r'^records_statistics', views.call_record_page, name="records_statistics"),
    url(r'^logout_link', views.logout_view, name="logout_link"),
    url(r'^evaluation', views.evaluation, name="evaluation"),
    url(r'^evaluate', views.evaluate, name="evaluate"),
    url(r'^customers/$', views.CustomerList.as_view(), name='customer-list'),
    url(r'customer/add/$', views.CustomerCreate.as_view(), name='customer-add'),
    url(r'customer/(?P<pk>[0-9]+)/$', views.CustomerUpdate.as_view(), name='customer-update'),
    url(r'customer/(?P<pk>[0-9]+)/delete/$', views.CustomerDelete.as_view(), name='customer-delete'),
    url(r'^discount_cards/$', views.DiscountCardList.as_view(), name='discount-card-list'),
    url(r'discount_card/add/$', views.DiscountCardCreate.as_view(), name='discount-card-add'),
    url(r'discount_card/(?P<pk>[0-9]+)/$', views.DiscountCardUpdate.as_view(), name='discount-card-update'),
    url(r'discount_card/(?P<pk>[0-9]+)/delete/$', views.DiscountCardDelete.as_view(), name='discount-card-delete'),
    url(r'^deliveries/$', views.DeliveryList.as_view(), name='delivery-list'),
    url(r'delivery/add/$', views.DeliveryCreate.as_view(), name='delivery-add'),
    url(r'delivery/(?P<pk>[0-9]+)/$', views.DeliveryUpdate.as_view(), name='delivery-update'),
    url(r'delivery/(?P<pk>[0-9]+)/delete/$', views.DeliveryDelete.as_view(), name='delivery-delete'),
    url(r'^delivery_orders/$', views.DeliveryOrderList.as_view(), name='delivery-order-list'),
    url(r'delivery_order/add/$', views.DeliveryOrderCreate.as_view(), name='delivery-order-add'),
    url(r'delivery_order/(?P<pk>[0-9]+)/$', views.DeliveryOrderUpdate.as_view(), name='delivery-order-update'),
    url(r'delivery_order/(?P<pk>[0-9]+)/delete/$', views.DeliveryOrderDelete.as_view(), name='delivery-order-delete'),
    url(r'incoming_call/$', views.IncomingCall.as_view(), name='incoming-call'),
    url(r'delivery/$', views.DeliveryView.as_view(), name='delivery'),
    url(r'^cooks_content_info', views.cooks_content_info, name='cooks_content_info'),
    url(r'^check_order_status', views.check_order_status, name='check_order_status'),
    url(r'^get_customers_menu', views.get_customers_menu, name='get_customers_menu'),
    url(r'^send_customers_menu', views.send_customers_menu, name='get_customers_menu'),
    url(r'^register_customer_order', views.register_customer_order, name='register_customer_order'),

    path('order-from-site/', views.order_from_site, name='order_from_site'),  # not use
    path('excel/', views.excel, name='excel'),

]