# Generated by Django 3.2.4 on 2023-08-09 08:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sber', '0003_alter_sbersettings_callback_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='SberTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата, время')),
                ('data', models.TextField(blank=True, null=True)),
                ('accepted', models.BooleanField(default=False, verbose_name='принято Сбером')),
                ('paid', models.BooleanField(default=False, verbose_name='клиент оплатил')),
            ],
            options={
                'verbose_name': 'Транзакции Сбера',
                'verbose_name_plural': 'Транзакции Сбера',
            },
        ),
    ]
