# Generated by Django 3.2.4 on 2023-08-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sber', '0004_sbertransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbertransaction',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
