# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 19:09


from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('note', models.CharField(max_length=500)),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0, "Price can't be negative!")])),
                ('avg_preparation_time', models.DurationField(verbose_name='Average preparation time.')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_number', models.IntegerField(unique_for_date=True, verbose_name='Daily Number')),
                ('open_time', models.DateTimeField(verbose_name='Open Time')),
                ('close_time', models.DateTimeField(null=True, verbose_name='Close Time')),
                ('content_completed', models.BooleanField(default=False, verbose_name='Content Completed')),
                ('supplement_completed', models.BooleanField(default=False, verbose_name='Supplement Completed')),
                ('total', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0, "Total can't be negative!")])),
                ('is_canceled', models.BooleanField(default=False, verbose_name='Is canceled')),
            ],
        ),
        migrations.CreateModel(
            name='OrderContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_timestamp', models.DateTimeField(null=True, verbose_name='Start Timestamp')),
                ('finish_timestamp', models.DateTimeField(null=True, verbose_name='Finish Timestamp')),
                ('is_in_grill', models.BooleanField(default=False, verbose_name='Is in grill')),
                ('is_canceled', models.BooleanField(default=False, verbose_name='Is canceled')),
                ('note', models.CharField(default='', max_length=500)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shaw_queue.Menu', verbose_name='Menu Item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shaw_queue.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default='False')),
            ],
        ),
        migrations.CreateModel(
            name='StaffCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shaw_queue.StaffCategory'),
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordercontent',
            name='staff_maker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shaw_queue.Staff', verbose_name='Staff Maker'),
        ),
        migrations.AddField(
            model_name='menu',
            name='can_be_prepared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shaw_queue.StaffCategory'),
        ),
    ]
