# Generated by Django 3.2.4 on 2025-04-19 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server1C',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=500)),
                ('ip_address', models.CharField(default='', max_length=500)),
                ('port', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('subnetwork', models.CharField(default='', max_length=10)),
                ('latitude', models.FloatField(default=55.196829, verbose_name='Широта')),
                ('longitude', models.FloatField(default=61.395762, verbose_name='Долгота')),
                ('default_remote_order_acceptor', models.BooleanField(default=False, help_text='Может быть выбрана ТОЛЬКО ОДНА точка.', verbose_name='Точка, принимающая интернет-заказы')),
                ('fullname', models.CharField(blank=True, default='', help_text='С указанием города. Важно вводить населенный пункт с указанием номера дома, но без номера квартиры, подъезда, этажа', max_length=500, verbose_name='полное название')),
                ('building', models.CharField(blank=True, default='', help_text='Для доставки', max_length=500, verbose_name='строение ')),
                ('building_name', models.CharField(blank=True, default='', help_text='Для доставки', max_length=500, verbose_name='название апартаментов')),
                ('city', models.CharField(blank=True, default='', help_text='Для доставки', max_length=500, verbose_name='город')),
                ('country', models.CharField(blank=True, default='', help_text='Для доставки', max_length=500, verbose_name='страна')),
                ('comment', models.CharField(blank=True, default='', help_text='Для доставки', max_length=500, verbose_name='комментарий по-умолчанию')),
                ('description', models.CharField(blank=True, default='', help_text='Для доставки, Географическая область, уточняющая до глобального соответствия', max_length=500, verbose_name='описание')),
                ('porch', models.CharField(blank=True, default='', help_text='Для доставки', max_length=500, verbose_name='подъезд')),
                ('sflat', models.CharField(blank=True, default='', help_text='Для доставки', max_length=500, verbose_name='Квартира')),
                ('sfloor', models.CharField(blank=True, default='1', help_text='Для доставки', max_length=500, verbose_name='Этаж')),
                ('phone', models.CharField(default='', help_text='Для доставки', max_length=200)),
                ('server_1c', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shaw_queue.server1c')),
            ],
        ),
    ]
