# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 05:43


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': (('can_cancel', 'User can cancel order.'), ('can_close', 'User can close order.'))},
        ),
        migrations.AlterModelOptions(
            name='ordercontent',
            options={'permissions': (('can_cancel', 'User can cancel order content.'), ('can_cook', 'User can cook order content'))},
        ),
        migrations.AddField(
            model_name='order',
            name='canceled_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canceler', to='shaw_queue.Staff', verbose_name='Canceled By'),
        ),
        migrations.AddField(
            model_name='order',
            name='closed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closer', to='shaw_queue.Staff', verbose_name='Closed By'),
        ),
        migrations.AddField(
            model_name='order',
            name='opened_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opener', to='shaw_queue.Staff', verbose_name='Opened By'),
        ),
        migrations.AddField(
            model_name='ordercontent',
            name='canceled_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_canceler', to='shaw_queue.Staff', verbose_name='Canceled By'),
        ),
    ]
