# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-21 15:51


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0003_ordercontent_grill_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='printed',
            field=models.BooleanField(default=False, verbose_name='Check Printed'),
        ),
    ]
