# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-01 20:04


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0005_auto_20170926_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_with_cash',
            field=models.BooleanField(default=True, verbose_name='Paid With Cash'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Is Paid'),
        ),
    ]
