# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-22 04:47


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0008_menu_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='eng_title',
            field=models.CharField(default='none', max_length=20),
            preserve_default=False,
        ),
    ]
