# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-05 04:41


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0012_order_prepared_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='super_guy',
            field=models.BooleanField(default='False'),
        ),
    ]
