# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-19 05:15


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0013_staff_super_guy'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_ready',
            field=models.BooleanField(default=False, verbose_name='Is Ready'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_voiced',
            field=models.BooleanField(default=False, verbose_name='Is Voiced'),
        ),
    ]
