# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-20 15:56


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0015_servery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='servery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shaw_queue.Servery', verbose_name='Servery'),
            preserve_default=False,
        ),
    ]
