# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-21 05:02


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0019_auto_20180106_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_grilling_shash',
            field=models.BooleanField(default=False, verbose_name='Shash Is Grilling'),
        ),
    ]
