# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-19 15:41


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0023_orderopinion_post_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PauseTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_timestamp', models.DateTimeField(null=True, verbose_name='Start Timestamp')),
                ('end_timestamp', models.DateTimeField(null=True, verbose_name='End Timestamp')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shaw_queue.Staff')),
            ],
        ),
    ]
