# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-15 05:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0024_pausetracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0, "Total can't be negative!")]),
        ),
        migrations.AddField(
            model_name='order',
            name='guid_1c',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_in_1c',
            field=models.BooleanField(default=False, verbose_name='Paid In 1C'),
        ),
        migrations.AddField(
            model_name='order',
            name='sent_to_1c',
            field=models.BooleanField(default=False, verbose_name='Sent To 1C'),
        ),
        migrations.AddField(
            model_name='servery',
            name='guid_1c',
            field=models.CharField(default='', max_length=100),
        ),
    ]
