# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-12 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0025_auto_20180415_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='hidden',
            field=models.BooleanField(default='False'),
        ),
    ]
