# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-18 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0026_menucategory_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('subnetwork', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='servery',
            name='service_point',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shaw_queue.ServicePoint'),
        ),
        migrations.AddField(
            model_name='staff',
            name='service_point',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shaw_queue.ServicePoint'),
        ),
    ]
