# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-23 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0027_auto_20180418_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='with_shashlyk',
            field=models.BooleanField(default=False, verbose_name='With Shashlyk'),
        ),
        migrations.AddField(
            model_name='order',
            name='with_shawarma',
            field=models.BooleanField(default=False, verbose_name='With Shawarma'),
        ),
    ]
