# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-13 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0028_auto_20180423_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20)),
                ('ip_address', models.CharField(default='', max_length=20)),
                ('service_point', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shaw_queue.ServicePoint')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='status_1c',
            field=models.IntegerField(default=200, verbose_name='1C Status'),
        ),
        migrations.AddField(
            model_name='servery',
            name='display_title',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='daily_number',
            field=models.IntegerField(verbose_name='Daily Number'),
        ),
    ]
