# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-27 12:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0029_auto_20180513_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ats_id', models.CharField(default='ID not set', max_length=250)),
                ('timepoint', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, default=datetime.timedelta(0), null=True)),
                ('record', models.CharField(default='Record path not set', max_length=256)),
                ('call_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shaw_queue.Staff', verbose_name='manager who accepted call')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name not set', max_length=30, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shaw_queue.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='Address not set', max_length=250)),
                ('obtain_timepoint', models.DateTimeField(blank=True, null=True)),
                ('delivered_timepoint', models.DateTimeField(blank=True, null=True)),
                ('prep_start_timepoint', models.DateTimeField(blank=True, null=True)),
                ('preparation_duration', models.DurationField(blank=True, default=datetime.timedelta(0), null=True)),
                ('delivery_duration', models.DurationField(blank=True, default=datetime.timedelta(0), null=True)),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shaw_queue.Customer', verbose_name='customer who ordered')),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shaw_queue.Delivery', verbose_name='inclusive delivery')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shaw_queue.Order', verbose_name='included order')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('discount', models.FloatField()),
                ('guid_1c', models.CharField(default='', max_length=100)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shaw_queue.Customer', verbose_name='owner of card')),
            ],
        ),
        migrations.AddField(
            model_name='calldata',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shaw_queue.Customer', verbose_name='customer who called'),
        ),
    ]
