# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-21 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0032_auto_20181003_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='ats_id',
            field=models.CharField(default='ID not set', max_length=250, unique=True),
        ),
    ]
