# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-07-31 17:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0034_order_start_shawarma_cooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='calldata',
            name='missed',
            field=models.BooleanField(default=False, verbose_name='Звонок пропущен'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='daily_number',
            field=models.IntegerField(default=0, unique_for_date=datetime.date.today, verbose_name='номер за день'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='is_delivered',
            field=models.BooleanField(default=False, verbose_name='доставлен'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='is_ready',
            field=models.BooleanField(default=False, verbose_name='готов к отправке'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='Имя не указано', max_length=30, null=True, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='address',
            field=models.CharField(default='Не указан', max_length=250, verbose_name='адрес'),
        ),
    ]
