# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-10-01 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0036_auto_20190808_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='start_shawarma_preparation',
            field=models.BooleanField(default=True, verbose_name='Start Shawarma Preparation'),
        ),
    ]
