# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-02-08 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0037_order_start_shawarma_preparation'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='prefered_payment',
            field=models.CharField(choices=[('CSH', 'Наличные'), ('CLS', 'Безнал'), ('MXD', 'Смешанная')], default='CSH', max_length=3),
        ),
        migrations.AddField(
            model_name='servery',
            name='payment_kiosk',
            field=models.BooleanField(default=True, verbose_name='Точка приёма платежей'),
        ),
    ]
