# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-03-19 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0039_auto_20200212_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAreaPolyCoord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_order', models.IntegerField(help_text='Вершины полигона должны быть перечислены в порядке правого обхода (по часовой стрелке).', verbose_name='Порядок вершины')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAreaPolygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Полигон', max_length=25, verbose_name='Название')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
            ],
        ),
        migrations.AddField(
            model_name='servicepoint',
            name='latitude',
            field=models.FloatField(default=55.196829, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='servicepoint',
            name='longitude',
            field=models.FloatField(default=61.395762, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='serviceareapolygon',
            name='service_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shaw_queue.ServicePoint'),
        ),
        migrations.AddField(
            model_name='serviceareapolycoord',
            name='polygon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shaw_queue.ServiceAreaPolygon'),
        ),
    ]
