# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-04-12 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0040_auto_20200319_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='moderation_needed',
            field=models.BooleanField(default=False, verbose_name='требуется модерация'),
        ),
        migrations.AddField(
            model_name='menu',
            name='customer_appropriate',
            field=models.BooleanField(default=False, verbose_name='Подходит для демонстрации покупателю'),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='customer_appropriate',
            field=models.BooleanField(default=False, verbose_name='Подходит для демонстрации покупателю'),
        ),
    ]
