# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-04-17 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0041_auto_20200412_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shaw_queue.StaffCategory'),
        ),
    ]
