# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-04-17 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0042_auto_20200417_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shaw_queue.Delivery', verbose_name='доставка'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='can_be_prepared_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shaw_queue.StaffCategory'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shaw_queue.MenuCategory'),
        ),
        migrations.AlterField(
            model_name='order',
            name='canceled_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canceler', to='shaw_queue.Staff', verbose_name='Canceled By'),
        ),
        migrations.AlterField(
            model_name='order',
            name='closed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closer', to='shaw_queue.Staff', verbose_name='Closed By'),
        ),
        migrations.AlterField(
            model_name='order',
            name='opened_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opener', to='shaw_queue.Staff', verbose_name='Opened By'),
        ),
        migrations.AlterField(
            model_name='order',
            name='prepared_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maker', to='shaw_queue.Staff'),
        ),
        migrations.AlterField(
            model_name='ordercontent',
            name='canceled_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_canceler', to='shaw_queue.Staff', verbose_name='Canceled By'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='service_point',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shaw_queue.ServicePoint'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='service_point',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shaw_queue.ServicePoint'),
        ),
    ]
