# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-04-26 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shaw_queue', '0043_auto_20200417_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='servery',
            name='default_remote_order_acceptor',
            field=models.BooleanField(default=False, help_text='Может быть выбрана ТОЛЬКО ОДНА касса на точку.',
                                      verbose_name='Касса, принимающая интернет-заказы'),
        ),
        migrations.AddField(
            model_name='servicepoint',
            name='default_remote_order_acceptor',
            field=models.BooleanField(default=False, help_text='Может быть выбрана ТОЛЬКО ОДНА точка.',
                                      verbose_name='Точка, принимающая интернет-заказы'),
        ),
    ]
