# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-04-27 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shaw_queue', '0045_menu_customer_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='customer_title',
            field=models.CharField(default='', max_length=200, verbose_name='Название для покупателя'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='customer_title',
            field=models.CharField(default='', max_length=200, verbose_name='Название для покупателя'),
        ),
    ]
