# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2021-04-03 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0050_auto_20210314_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='macroproductcontent',
            name='menu_title',
            field=models.CharField(default='', max_length=200, verbose_name='Название для меню'),
        ),
    ]
