# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2021-04-10 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0052_macroproduct_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_preorder',
            field=models.BooleanField(default=False, verbose_name='Предзаказ'),
        ),
    ]
