# Generated by Django 3.2.4 on 2021-06-26 15:31

from django.db import migrations, models
import django.db.models.deletion
import shaw_queue.models


class Migration(migrations.Migration):
    dependencies = [
        ('shaw_queue', '0053_order_is_preorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server1C',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=500)),
                ('ip_address', models.CharField(default='', max_length=500)),
                ('port', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='order',
            field=models.ForeignKey(limit_choices_to=shaw_queue.models.limit_order_choises_by_date,
                                    on_delete=django.db.models.deletion.CASCADE, to='shaw_queue.order',
                                    verbose_name='включеный заказ'),
        ),
        migrations.AddField(
            model_name='servicepoint',
            name='server_1c',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='shaw_queue.server1c'),
        ),
    ]
