# Generated by Django 3.2.4 on 2022-10-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0055_staff_fired'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='from_site',
            field=models.BooleanField(default=False, verbose_name='From site'),
        ),
    ]
