# Generated by Django 3.2.4 on 2022-10-05 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0056_order_from_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servery',
            name='service_point',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shaw_queue.servicepoint'),
        ),
    ]
