# Generated by Django 3.2.4 on 2022-10-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0057_alter_servery_service_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup',
            field=models.BooleanField(default=False, verbose_name='Самовывоз'),
        ),
    ]
