# Generated by Django 3.2.4 on 2022-11-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0058_order_pickup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='prefered_payment',
            field=models.CharField(choices=[('CSH', 'Наличные'), ('CLS', 'Безнал'), ('ONL', 'Сайт'), ('MXD', 'Смешанная')], default='ONL', max_length=3, verbose_name='Вид оплаты'),
        ),
    ]
