# Generated by Django 3.2.4 on 2022-11-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0062_auto_20221123_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookingtime',
            name='categories',
            field=models.ManyToManyField(blank=True, to='shaw_queue.MenuCategory', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='cookingtime',
            name='products',
            field=models.ManyToManyField(blank=True, to='shaw_queue.Menu', verbose_name='Товары'),
        ),
    ]
