# Generated by Django 3.2.4 on 2022-11-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0063_auto_20221123_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookingtime',
            name='default',
            field=models.BooleanField(default=False, verbose_name='по умолчанию'),
        ),
    ]
