# Generated by Django 3.2.4 on 2022-12-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0064_alter_cookingtime_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_pickup',
            field=models.BooleanField(default=False, verbose_name='С собой'),
        ),
    ]
