# Generated by Django 3.2.4 on 2022-12-12 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0066_cookingtimerordercontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cookingtimerordercontent',
            old_name='datetime',
            new_name='date_time',
        ),
    ]
