# Generated by Django 3.2.4 on 2023-02-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0068_ordercontent_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='QR_required',
            field=models.BooleanField(default=False, verbose_name='QR обязателен'),
        ),
    ]
