# Generated by Django 3.2.4 on 2023-04-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0070_alter_ordercontent_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepoint',
            name='building',
            field=models.CharField(default='', help_text='Для доставки', max_length=500, verbose_name='строение '),
        ),
        migrations.AddField(
            model_name='servicepoint',
            name='building_name',
            field=models.CharField(default='', help_text='Для доставки', max_length=500, verbose_name='название апартаментов'),
        ),
        migrations.AddField(
            model_name='servicepoint',
            name='city',
            field=models.CharField(default='', help_text='Для доставки', max_length=500, verbose_name='город'),
        ),
        migrations.AddField(
            model_name='servicepoint',
            name='comment',
            field=models.CharField(default='', help_text='Для доставки', max_length=500, verbose_name='комментарий по-умолчанию'),
        ),
        migrations.AddField(
            model_name='servicepoint',
            name='country',
            field=models.CharField(default='', help_text='Для доставки', max_length=500, verbose_name='страна'),
        ),
        migrations.AddField(
            model_name='servicepoint',
            name='description',
            field=models.CharField(default='', help_text='Для доставки, Географическая область, уточняющая до глобального соответствия', max_length=500, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='servicepoint',
            name='fullname',
            field=models.CharField(default='', help_text='С указанием города. Важно вводить населенный пункт с указанием номера дома, но без номера квартиры, подъезда, этажа', max_length=500, verbose_name='полное название'),
        ),
        migrations.AddField(
            model_name='servicepoint',
            name='porch',
            field=models.CharField(default='', help_text='Для доставки', max_length=500, verbose_name='подъезд'),
        ),
        migrations.AddField(
            model_name='servicepoint',
            name='sflat',
            field=models.CharField(default='', help_text='Для доставки', max_length=500, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='servicepoint',
            name='sfloor',
            field=models.CharField(default='1', help_text='Для доставки', max_length=500, verbose_name='Этаж'),
        ),
    ]
