# Generated by Django 3.2.4 on 2023-04-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0071_auto_20230403_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepoint',
            name='building',
            field=models.CharField(blank=True, default='', help_text='Для доставки', max_length=500, verbose_name='строение '),
        ),
        migrations.AlterField(
            model_name='servicepoint',
            name='building_name',
            field=models.CharField(blank=True, default='', help_text='Для доставки', max_length=500, verbose_name='название апартаментов'),
        ),
        migrations.AlterField(
            model_name='servicepoint',
            name='city',
            field=models.CharField(blank=True, default='', help_text='Для доставки', max_length=500, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='servicepoint',
            name='comment',
            field=models.CharField(blank=True, default='', help_text='Для доставки', max_length=500, verbose_name='комментарий по-умолчанию'),
        ),
        migrations.AlterField(
            model_name='servicepoint',
            name='country',
            field=models.CharField(blank=True, default='', help_text='Для доставки', max_length=500, verbose_name='страна'),
        ),
        migrations.AlterField(
            model_name='servicepoint',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Для доставки, Географическая область, уточняющая до глобального соответствия', max_length=500, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='servicepoint',
            name='fullname',
            field=models.CharField(blank=True, default='', help_text='С указанием города. Важно вводить населенный пункт с указанием номера дома, но без номера квартиры, подъезда, этажа', max_length=500, verbose_name='полное название'),
        ),
        migrations.AlterField(
            model_name='servicepoint',
            name='porch',
            field=models.CharField(blank=True, default='', help_text='Для доставки', max_length=500, verbose_name='подъезд'),
        ),
        migrations.AlterField(
            model_name='servicepoint',
            name='sflat',
            field=models.CharField(blank=True, default='', help_text='Для доставки', max_length=500, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='servicepoint',
            name='sfloor',
            field=models.CharField(blank=True, default='1', help_text='Для доставки', max_length=500, verbose_name='Этаж'),
        ),
    ]
