# Generated by Django 3.2.4 on 2023-04-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0073_servicepoint_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_daily_number',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Delivery Daily Number'),
        ),
    ]
