# Generated by Django 3.2.4 on 2023-04-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0074_order_delivery_daily_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='close_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Close Time'),
        ),
    ]
