# Generated by Django 3.2.4 on 2023-08-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0075_alter_order_close_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_with_sms',
            field=models.BooleanField(default=False, verbose_name='Paid With SMS'),
        ),
    ]
