# Generated by Django 3.2.4 on 2023-10-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0077_auto_20231016_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_grilling_burger',
            field=models.BooleanField(default=False, verbose_name='Burger Is Grilling'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_preparing_coffee',
            field=models.BooleanField(default=False, verbose_name='Coffee Is Preparing'),
        ),
    ]
