# Generated by Django 3.2.4 on 2023-11-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0078_auto_20231016_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_title',
            field=models.CharField(default='', max_length=200, verbose_name='Название для меню'),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='menu_title',
            field=models.CharField(default='', max_length=200, verbose_name='Название для меню'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='menu_title',
            field=models.CharField(default='', max_length=200, verbose_name='Название для меню'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='menu_title',
            field=models.CharField(default='', max_length=200, verbose_name='Название для меню'),
        ),
    ]
