# Generated by Django 3.2.4 on 2023-11-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0079_auto_20231106_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentoption',
            name='menu_title',
            field=models.CharField(default='', max_length=200, verbose_name='Название для меню'),
        ),
        migrations.AddField(
            model_name='sizeoption',
            name='menu_title',
            field=models.CharField(default='', max_length=200, verbose_name='Название для меню'),
        ),
    ]
