# Generated by Django 3.2.4 on 2023-11-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaw_queue', '0081_macroproduct_menu_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='macroproduct',
            options={'ordering': ('ordering',)},
        ),
        migrations.AddField(
            model_name='macroproduct',
            name='ordering',
            field=models.IntegerField(default=0, verbose_name='ordering'),
        ),
    ]
