# Generated by Django 3.2.4 on 2023-12-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='title2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='title3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
