# Generated by Django 3.2.4 on 2025-01-28 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_ikoorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IkoOrder',
        ),
    ]
