# Generated by Django 3.2.4 on 2023-03-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('vpbx_api_key', models.CharField(max_length=200, verbose_name='Уникальный код вашей АТС')),
                ('vpbx_api_salt', models.CharField(max_length=200, verbose_name='Ключ для создания подписи')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
            ],
        ),
    ]
