# Generated by Django 3.2.4 on 2023-03-18 04:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangoSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('test_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('vpbx_api_key', models.CharField(max_length=200, verbose_name='Уникальный код вашей АТС')),
                ('vpbx_api_salt', models.CharField(max_length=200, verbose_name='Ключ для создания подписи')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
            ],
        ),
        migrations.CreateModel(
            name='SMSHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=500)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата, время')),
                ('success', models.BooleanField(default=False, verbose_name='success')),
                ('result', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
