# Generated by Django 3.2.4 on 2022-11-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('excel', models.FileField(blank=True, null=True, upload_to='excels', verbose_name='excel')),
            ],
        ),
    ]
