# Generated by Django 3.2.4 on 2023-08-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_popularnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteBTN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=1000)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='img/notes/category_pictures', verbose_name='Иконка')),
                ('position', models.IntegerField(verbose_name='position')),
            ],
        ),
    ]
