# Generated by Django 3.2.4 on 2023-08-09 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_notebtn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notebtn',
            options={'ordering': ('position', 'note')},
        ),
        migrations.AddField(
            model_name='notebtn',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
