# Generated by Django 3.2.4 on 2023-08-09 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230809_0721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notebtn',
            options={'ordering': ('active', 'position', 'note')},
        ),
    ]
