# Generated by Django 3.2.4 on 2024-06-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iko', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iikosettings',
            name='currenttoken',
            field=models.CharField(default='', max_length=200),
        ),
    ]
