# Generated by Django 3.2.4 on 2024-06-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iko', '0002_iikosettings_currenttoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='iikosettings',
            name='last_getting',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
