# Generated by Django 3.2.4 on 2025-02-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iko', '0005_iikosettings_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='iikosettings',
            name='last_update_token',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
