# Generated by Django 3.2.4 on 2025-02-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iko', '0008_auto_20250205_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio', verbose_name='audio')),
            ],
        ),
    ]
