# Generated by Django 3.2.4 on 2024-06-14 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iiko', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='iikoSettings',
        ),
    ]
