# Generated by Django 3.2.4 on 2024-06-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiko', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iikosettings',
            name='url',
        ),
        migrations.AlterField(
            model_name='iikosettings',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
